"""Generate synthetic maintenance logs for training the classifier."""
"""
generate_logs.py — Synthetic maintenance-log generator for a fault classifier.

============================ SYNTHETIC DATA NOTICE ============================
ALL DATA PRODUCED BY THIS SCRIPT IS SYNTHETIC. It is generated by template
variation and paraphrasing of a small set of hand-written seed examples.
It does NOT come from any real plant, CMMS, SCADA/PLC historian, or vendor.
Equipment IDs, timestamps, fault notes, resolutions, and downtimes are
fabricated for a PORTFOLIO / fine-tuning demonstration only and must not be
used for real maintenance decisions or presented as real operational records.
==============================================================================

Output: data/maintenance_logs/historical_logs.json
  A list of objects: log_id, timestamp, equipment_id, fault_category,
  log_text, resolution, downtime_minutes.

Approach:
  - 5 fault categories, >=40 records each (>=200 total).
  - Each record is built by combining a category's symptom/context/resolution
    fragments (derived from the seeds) into a terse, engineer-style note.
  - Deterministic: RNG is seeded so reruns are reproducible.
"""

import json
import os
import random
from datetime import datetime, timedelta

# Reproducible output. Change/remove the seed for fresh variety.
RNG = random.Random(42)

OUT_PATH = "data/maintenance_logs/historical_logs.json"
PER_CATEGORY = 45  # >= 40 required; 5 * 45 = 225 total

CATEGORIES = [
    "bearing_fault",
    "lubrication_issue",
    "electrical_fault",
    "calibration_drift",
    "software_anomaly",
]

# ---------------------------------------------------------------------------
# SEED EXAMPLES — hand-written. Replace these with your own 3-per-category.
# The generator paraphrases/recombines these; better seeds -> better output.
# ---------------------------------------------------------------------------
SEED_EXAMPLES = {
    "bearing_fault": [
        "DE bearing running hot, 78C at the housing. Audible growl at 1480 rpm. Vibration band 2x line freq elevated.",
        "Outer race spalling suspected on conveyor head pulley. Grease purge showed metal flake. Noise increases under load.",
        "NDE bearing vibration trending up over 3 shifts, 6.1 mm/s RMS. Slight axial play felt by hand.",
    ],
    "lubrication_issue": [
        "Gearbox oil level low, sight glass below min. Slight weep at output seal. Oil dark, due for change.",
        "Auto-luber empty on line 3 drive, no grease delivered for 2 days. Bearing temp creeping up.",
        "Oil sample flagged high particle count, ISO code out of spec. Filter dP high, bypass open.",
    ],
    "electrical_fault": [
        "VFD tripped on overcurrent, fault F012. Motor megger 2.1 Mohm, marginal. Phase imbalance ~6%.",
        "Contactor chattering on starter, coil voltage low. Aux contact pitted. Intermittent drop-out under load.",
        "Heater element open on circuit 4, no current draw. Thermal overload reset would not hold.",
    ],
    "calibration_drift": [
        "Flow transmitter reading 4% high vs reference. Zero drifted, last cal 14 months ago. Loop check ok.",
        "Temp RTD on reactor showing 3C offset vs handheld. Drift since last PM. Linear across range.",
        "Load cell on hopper out of cal, weight readback off by 12 kg. Span needs re-trim.",
    ],
    "software_anomaly": [
        "PLC comms dropout to remote IO rack, watchdog timeout. HMI froze, recovered on restart.",
        "Batch sequence stuck on step 7, logic waiting on flag that never set. Manual force to advance.",
        "SCADA tag quality bad on 6 points after firmware update. Driver mismatch suspected.",
    ],
}

# ---------------------------------------------------------------------------
# Fragment libraries per category (terse, engineer voice). These drive the
# template variation; phrasing is intentionally clipped, abbreviations kept.
# ---------------------------------------------------------------------------
SYMPTOMS = {
    "bearing_fault": [
        "DE bearing running hot at {temp}C", "NDE bearing vibration up to {vib} mm/s RMS",
        "audible growl at {rpm} rpm", "outer race spalling suspected", "metal flake in grease purge",
        "axial play felt by hand", "vibration band 2x line freq elevated", "bearing noise rises under load",
        "housing temp trending up over {shifts} shifts", "rumble at the drive end", "inner race defect freq present in FFT",
    ],
    "lubrication_issue": [
        "gearbox oil level below min on sight glass", "auto-luber empty, no grease for {days} days",
        "oil sample high particle count, ISO out of spec", "filter dP high, bypass open", "oil dark and overdue for change",
        "weep at output seal", "grease line blocked to bearing", "oil temp high, viscosity dropping",
        "no oil flow indicated at the pump", "water ingress in sump, oil milky",
    ],
    "electrical_fault": [
        "VFD tripped on overcurrent, fault {fcode}", "motor megger {meg} Mohm, marginal", "phase imbalance ~{imb}%",
        "contactor chattering on starter", "aux contact pitted", "heater element open, no current draw",
        "thermal overload would not reset", "loose lug on terminal {term}, discoloration", "intermittent drop-out under load",
        "ground fault on feeder, trip on close", "encoder signal dropping, drive faults",
    ],
    "calibration_drift": [
        "flow transmitter reading {pct}% high vs reference", "temp RTD showing {off}C offset vs handheld",
        "load cell off by {kg} kg on readback", "zero drifted, last cal {months} months ago",
        "pressure tx span out of trim", "drift linear across range", "level reading creeping vs manual dip",
        "pH probe slow and offset", "analyzer out of spec vs grab sample", "4-20 loop reads low at 50% span",
    ],
    "software_anomaly": [
        "PLC comms dropout to remote IO, watchdog timeout", "HMI froze, recovered on restart",
        "batch sequence stuck on step {step}", "SCADA tag quality bad on {pts} points",
        "logic waiting on flag that never set", "driver mismatch after firmware update",
        "alarm flood from a single stuck bit", "OPC server lost connection intermittently",
        "recipe download failed checksum", "timestamp skew between PLC and historian",
    ],
}

CONTEXTS = [
    "on line {n} drive", "at the conveyor head pulley", "on the main compressor",
    "on pump skid {n}", "in the mixing area", "on the packaging line", "at the reactor feed",
    "on the cooling tower fan", "on extruder {n}", "in the utilities building", "on the palletizer",
]

RESOLUTIONS = {
    "bearing_fault": [
        "Replaced bearing, re-greased to spec, vibration back to {vib} mm/s.",
        "Swapped DE bearing and seal, aligned coupling, retested ok.",
        "Repacked grease, monitored temp, scheduled bearing change at next PM.",
        "Pressed in new bearing, checked fit and clearance, returned to service.",
    ],
    "lubrication_issue": [
        "Topped up oil, traced and fixed seal weep, logged for reseal.",
        "Refilled and reset auto-luber, verified grease delivery at the point.",
        "Changed oil and filter, took fresh sample, dP back to normal.",
        "Cleared blocked grease line, purged bearing, confirmed flow.",
    ],
    "electrical_fault": [
        "Re-terminated lug, torqued to spec, thermal scan clean after.",
        "Replaced contactor, checked coil voltage, no further chatter.",
        "Megger retest after dry-out, motor back in spec, reset VFD.",
        "Swapped heater element, verified current draw balanced.",
    ],
    "calibration_drift": [
        "Re-zeroed and trimmed span, loop verified against reference.",
        "Recalibrated transmitter, updated cal record, within tolerance.",
        "Re-trimmed load cell span, weight readback matched test weights.",
        "Replaced drifting RTD, calibrated loop, offset cleared.",
    ],
    "software_anomaly": [
        "Restarted IO scanner, comms restored, added watchdog alarm.",
        "Forced step to advance, patched logic for missing flag, retested batch.",
        "Reloaded matching driver, tag quality good, documented firmware rev.",
        "Cycled OPC server, reseated network, monitored for recurrence.",
    ],
}

# Realistic downtime ranges (minutes) per fault type.
DOWNTIME_RANGES = {
    "bearing_fault": (90, 480),
    "lubrication_issue": (20, 180),
    "electrical_fault": (45, 360),
    "calibration_drift": (15, 120),
    "software_anomaly": (10, 240),
}

EQUIP_PREFIXES = [
    "DRIVE-LINE{n}-A", "DRIVE-LINE{n}-B", "CONV-BELT-{nn}", "PUMP-SKID-{nn}",
    "MOTOR-{nn}", "VFD-LINE{n}", "GEARBOX-{nn}", "RTD-REACT-{nn}",
    "PLC-RACK-{nn}", "COMP-{nn}", "EXTRUDER-{n}",
]

START = datetime(2023, 1, 1)
END = datetime(2025, 12, 31, 23, 59)
_SPAN_SECONDS = int((END - START).total_seconds())


def _fill(text):
    """Substitute any {placeholder}s with realistic random values."""
    return text.format(
        temp=RNG.randint(70, 95), vib=round(RNG.uniform(4.0, 11.0), 1),
        rpm=RNG.choice([980, 1180, 1480, 1770, 2950]), shifts=RNG.randint(2, 6),
        days=RNG.randint(1, 5), fcode=f"F{RNG.randint(1, 99):03d}",
        meg=round(RNG.uniform(1.5, 4.0), 1), imb=RNG.randint(4, 12),
        term=RNG.choice(["A1", "B2", "C3", "L2", "T3"]),
        pct=RNG.randint(2, 8), off=RNG.randint(2, 6), kg=RNG.randint(5, 40),
        months=RNG.randint(6, 18), step=RNG.randint(2, 14), pts=RNG.randint(2, 12),
        n=RNG.randint(1, 6), nn=f"{RNG.randint(1, 24):02d}",
    )


def _equipment_id():
    return _fill(RNG.choice(EQUIP_PREFIXES))


def _timestamp():
    ts = START + timedelta(seconds=RNG.randint(0, _SPAN_SECONDS))
    # Bias toward working hours so timestamps read realistically.
    ts = ts.replace(hour=RNG.randint(6, 22), minute=RNG.randint(0, 59), second=0)
    return ts.isoformat()


def _log_text(category):
    """One or two clipped symptom clauses + a context, engineer style."""
    n_sym = RNG.choice([1, 1, 2])  # mostly single clause, sometimes two
    syms = RNG.sample(SYMPTOMS[category], n_sym)
    ctx = _fill(RNG.choice(CONTEXTS))
    body = ". ".join(_fill(s) for s in syms)
    # Occasionally lead with the context, sometimes trail it — vary structure.
    if RNG.random() < 0.5:
        return f"{body} {ctx}."
    return f"{ctx.capitalize()}: {body}."


def generate():
    records = []
    counter = 1
    for category in CATEGORIES:
        seen = set()
        made = 0
        # Try until we hit the per-category target with unique log_text.
        while made < PER_CATEGORY:
            text = _log_text(category)
            if text in seen:
                continue
            seen.add(text)
            lo, hi = DOWNTIME_RANGES[category]
            records.append({
                "log_id": f"LOG-{counter:04d}",
                "timestamp": _timestamp(),
                "equipment_id": _equipment_id(),
                "fault_category": category,
                "log_text": text,
                "resolution": _fill(RNG.choice(RESOLUTIONS[category])),
                "downtime_minutes": RNG.randint(lo, hi),
            })
            counter += 1
            made += 1
    RNG.shuffle(records)  # interleave categories so the file isn't blocked
    return records


def summarize(records):
    counts = {c: 0 for c in CATEGORIES}
    for r in records:
        counts[r["fault_category"]] += 1

    print("=" * 60)
    print(f"Generated {len(records)} synthetic maintenance logs")
    print("=" * 60)
    print("Per-category counts:")
    for c in CATEGORIES:
        print(f"  {c:18s}: {counts[c]}")
    print("\nSample entries (2 per category):")
    for c in CATEGORIES:
        samples = [r for r in records if r["fault_category"] == c][:2]
        print(f"\n--- {c} ---")
        for s in samples:
            print(f"  [{s['log_id']}] {s['timestamp']}  {s['equipment_id']}  "
                  f"({s['downtime_minutes']} min)")
            print(f"    log: {s['log_text']}")
            print(f"    fix: {s['resolution']}")


def main():
    records = generate()
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(records, f, indent=2)
    print(f"Wrote {len(records)} records to {OUT_PATH}\n")
    summarize(records)


if __name__ == "__main__":
    main()